# Generated by Django 2.1.4 on 2019-01-04 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='from_ava',
            new_name='user_message',
        ),
    ]
