# Generated by Django 2.1.4 on 2019-01-10 01:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190104_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceBreaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2047)),
                ('shown', models.BigIntegerField()),
                ('swapped', models.BigIntegerField()),
                ('responded', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IceBreakerMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.Message')),
                ('swapped', models.BooleanField(default=False)),
                ('icebreaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.IceBreaker')),
            ],
            bases=('chat.message',),
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.Message')),
                ('text', models.CharField(max_length=2047)),
                ('user_author', models.BooleanField(default=True)),
            ],
            bases=('chat.message',),
        ),
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_message',
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
