# Generated by Django 2.1.4 on 2019-01-10 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20190110_0102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IceBreakerMessage',
        ),
        migrations.DeleteModel(
            name='TextMessage',
        ),
        migrations.AddField(
            model_name='message',
            name='icebreaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.IceBreaker'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_icebreaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_user_author',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='swapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(default='default', max_length=2047),
            preserve_default=False,
        ),
    ]
