# Generated by Django 2.1.4 on 2019-01-18 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190110_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2047)),
                ('responded', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='icebreaker',
            name='responded',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='icebreaker',
            name='shown',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='icebreaker',
            name='swapped',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icebreaker',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Topic'),
        ),
    ]
