# Generated by Django 2.1.4 on 2019-01-19 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20190118_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2047)),
                ('shown', models.BigIntegerField(default=0)),
                ('swapped', models.BigIntegerField(default=0)),
                ('responded', models.BigIntegerField(default=0)),
                ('is_icebreaker', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='icebreaker',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='message',
            name='icebreaker',
        ),
        migrations.AddField(
            model_name='message',
            name='is_question',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='IceBreaker',
        ),
        migrations.AddField(
            model_name='message',
            name='next_questions',
            field=models.ManyToManyField(blank=True, related_name='responded_to', to='chat.Question'),
        ),
        migrations.AddField(
            model_name='message',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Question'),
        ),
    ]
