# Generated by Django 2.1.4 on 2019-01-22 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20190119_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='next_questions',
            new_name='last_questions',
        ),
    ]
