# Generated by Django 2.1.4 on 2019-01-22 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20190122_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='last_questions',
        ),
        migrations.AddField(
            model_name='message',
            name='last_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_responses', to='chat.Question'),
        ),
    ]
