# Generated by Django 2.1.4 on 2019-01-25 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20190122_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2047)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown', models.BigIntegerField(default=0)),
                ('responded', models.BigIntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Answer')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='last_question',
        ),
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='swapped',
        ),
        migrations.AddField(
            model_name='questionanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='questions',
            field=models.ManyToManyField(through='chat.QuestionAnswers', to='chat.Question'),
        ),
        migrations.AddField(
            model_name='message',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Answer'),
        ),
    ]
