# Generated by Django 2.1.4 on 2019-01-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20190125_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswers',
            options={'ordering': ('responded',)},
        ),
        migrations.AlterField(
            model_name='question',
            name='shown',
            field=models.BigIntegerField(default=1),
        ),
    ]
