# Generated by Django 2.1.4 on 2019-02-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190209_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_ordering',
            field=models.IntegerField(default=0),
        ),
    ]
